<a href="https://colab.research.google.com/github/HEMNATH77/numpy-tutorials/blob/main/Numpy_Basics_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing numpy as np

In [ ]:
import numpy as np


variable declarations

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b=np.array([9.0,8.0,7.0],)
print(b)

[9. 8. 7.]


get dimensions of the variable

In [ ]:
a.ndim
b.ndim

1

get shape(rows,columns)

In [ ]:
c=np.array([[2,3,4],[4,5,6]])
print(c)

[[2 3 4]
 [4 5 6]]


In [ ]:
c.shape

(2, 3)

In [ ]:
a.shape

(4,)

get datatype

In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

get size

In [ ]:
a.itemsize

8

In [ ]:
c.itemsize

8

getting total size

In [ ]:
a.size

4

In [ ]:
a.size*a.itemsize

32

In [ ]:
a.nbytes

32