Accessing the specific elements,rows,columns,etc....

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

getting a specific element [r, c]

In [4]:
a[1, 4]

10

In [6]:
a[1, 3]

9

Getting a specific row

In [7]:
a[0, :]

array([1, 2, 3, 4, 5])

In [8]:
a[1, :]

array([ 6,  7,  8,  9, 10])

Getting a specific column

In [9]:
a[:, 2]

array([3, 8])

In [10]:
a[:, 1]

array([2, 7])

By [start index:end index:stepsize]

In [11]:
a[0, 1:4:1]

array([2, 3, 4])

In [14]:
a[1, 0:3:2]

array([6, 8])

In [16]:
a[1,3]=77
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8 77 10]]


In [17]:
a[:,3]=55
print(a)

[[ 1  2  3 55  5]
 [ 6  7  8 55 10]]


In [18]:
a[:,3]=[1,2]

In [19]:
print(a)

[[ 1  2  3  1  5]
 [ 6  7  8  2 10]]
