3D examples

In [ ]:
import numpy as np

In [ ]:
a=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


Get a specific element (0,row,column)

In [ ]:
a[:,1,0]


array([3])

Replace a element

In [ ]:
a[:,1,:]

array([[3, 4]])

In [ ]:
a[:,1,:]=[[9,9]]
print(a)

[[[1 2]
  [9 9]
  [5 6]
  [7 8]]]


Initializing different types of array

0's matrix (shape,dimension)

In [ ]:
np.zeros([2,2],dtype="int32")

array([[0, 0],
       [0, 0]], dtype=int32)

1's matrix (shape,dimensions)

In [ ]:
np.ones([2,3],dtype="int32")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

for any other number(shape(dimension),value)

In [ ]:
np.full([2,3],12)

array([[12, 12, 12],
       [12, 12, 12]])

In [3]:
import numpy as np

In [4]:
a=([1,2,3,4,5])

In [5]:
np.full_like(a,4)

array([4, 4, 4, 4, 4])

Random decimal numbers   
np.random.rand(rows,columns)

In [6]:
np.random.rand(4,2)

array([[0.42251415, 0.99589513],
       [0.62360385, 0.76259472],
       [0.75259338, 0.0982968 ],
       [0.14885346, 0.95286212]])

Random integer values


np.random.randint(start_value)
       

np.random.randint(start_value,size(dimension))       

In [18]:
np.random.randint(3)

2

In [20]:
np.random.randint(3,size=(2,3))

array([[0, 1, 1],
       [0, 2, 1]])