Identity Matrix

In [1]:
import numpy as np

In [2]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Repeat an array

np.repeat(array,size,axis=0(or)1)

In [4]:
a=np.array([1,2,3])

In [15]:
b1=np.repeat(a,3)
print(b1)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [17]:
a=np.array([[1,2,3]])
b1=np.repeat(a,3,axis=0)
print(b1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Copying Array


In [25]:
a=np.array([1,2,3,4,5])
b=a
print(b)

[1 2 3 4 5]


In [22]:
b[1]=100
print(b)

[  1 100   3   4   5]


In [23]:
print(a)

[  1 100   3   4   5]


In [28]:
c=([5,6,7,8])
d=a.copy()
print(d)

[1 2 3 4 5]


Mathematics

In [30]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [31]:
a+3

array([4, 5, 6, 7, 8])

In [32]:
a-3

array([-2, -1,  0,  1,  2])

In [33]:
a*2

array([ 2,  4,  6,  8, 10])

In [34]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [35]:
b=np.array([6,7,8,9,7])
a+b

array([ 7,  9, 11, 13, 12])

In [37]:
b ** 2

array([36, 49, 64, 81, 49])

Trignomentry

In [38]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [39]:
np.cos(b)

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026,  0.75390225])

In [41]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

Linear Algebra

In [43]:
a=np.array([1,2,3],dtype="int32")
print(a)

[1 2 3]


In [46]:
a=np.ones((2,3),dtype="int32")
print(a)

[[1 1 1]
 [1 1 1]]


In [48]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [49]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

To find determinant

In [50]:
a=np.identity(2)
np.linalg.det(a)

1.0

Statistics


In [51]:
stats=np.array([1,2,3,4,5])
print(stats)

[1 2 3 4 5]


In [55]:
np.min(stats,axis=0)

1

In [57]:
np.max(stats,axis=0)

5

In [61]:
b=np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.max(b,axis=1)

array([3, 6])

In [63]:
np.sum(b,axis=0)

array([5, 7, 9])