Reorganizing Arrays

In [2]:
import numpy as np

In [7]:
a=np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(a)

b=a.reshape((5,2))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Vertical Stacking vectors



In [12]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

np.vstack(([a,b]))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Horizontal Stack

In [13]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])