In [1]:
import numpy as np

In [28]:
# Load  and Save data

In [2]:
a=np.array([1,2,3])


In [6]:
np.save('my_array.npy',a)
print(a)

[1 2 3]


In [4]:
load=np.load('my_array.npy')


In [5]:
print(load)

[1 2 3]


In [8]:
b=np.array([1,2,3,4])
np.savetxt('my_array.txt',b,delimiter=',')

In [11]:
loaded=np.loadtxt('my_array.txt',delimiter=',')
print(loaded)

[1. 2. 3. 4.]


In [16]:
f=np.genfromtxt('np data.txt',delimiter=',')
print(f)


[[1. 2. 3. 4. 5. 6. 7. 8. 9. 3.]
 [2. 3. 4. 5. 6. 7. 8. 9. 1. 2.]
 [3. 4. 3. 4. 3. 4. 5. 2. 3. 4.]]


In [27]:
# Handling Csv Files with Pandas

In [17]:
import pandas as pd

In [21]:
df=pd.read_csv('annual-enterprise-survey-2023-financial-year-provisional-size-bands.csv')

In [22]:
print(df)

       year industry_code_ANZSIC               industry_name_ANZSIC  \
0      2011                    A  Agriculture, Forestry and Fishing   
1      2011                    A  Agriculture, Forestry and Fishing   
2      2011                    A  Agriculture, Forestry and Fishing   
3      2011                    A  Agriculture, Forestry and Fishing   
4      2011                    A  Agriculture, Forestry and Fishing   
...     ...                  ...                                ...   
20119  2023                  all                     All Industries   
20120  2023                  all                     All Industries   
20121  2023                  all                     All Industries   
20122  2023                  all                     All Industries   
20123  2023                  all                     All Industries   

        rme_size_grp                                         variable  \
0                a_0                                    Activity unit   
1

In [23]:
g=df.values
print(g)

[[2011 'A' 'Agriculture, Forestry and Fishing' ... 'Activity unit'
  '46134' 'COUNT']
 [2011 'A' 'Agriculture, Forestry and Fishing' ...
  'Rolling mean employees' '0' 'COUNT']
 [2011 'A' 'Agriculture, Forestry and Fishing' ...
  'Salaries and wages paid' '279' 'DOLLARS(millions)']
 ...
 [2023 'all' 'All Industries' ... 'Operating profit before tax' '103616'
  'DOLLARS(millions)']
 [2023 'all' 'All Industries' ... 'Total assets' '2831894'
  'DOLLARS(millions)']
 [2023 'all' 'All Industries' ... 'Fixed tangible assets' '681890'
  'DOLLARS(millions)']]
