In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


Attributes

In [4]:
a.shape

(4,)

In [5]:
a.size

4

In [6]:
a.dtype

dtype('int64')

In [7]:
a.ndim

1

Indexing

In [9]:
a[1]


2

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
a[1,2]

6

Slicing

In [13]:
x=np.array([1,2,3,4,5,6,7,8])
print(x)

[1 2 3 4 5 6 7 8]


In [16]:
a[1:8:1]

array([[4, 5, 6]])

Built in functions

In [19]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
a=np.ones((1,3))
print(a)

[[1. 1. 1.]]


In [25]:
a=np.full((2,3),2)
print(a)

[[2 2 2]
 [2 2 2]]


Mathematical Operations

In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])


In [27]:
np.add(a,b)

array([5, 7, 9])

In [29]:
np.subtract(a,b)

array([-3, -3, -3])

In [30]:
np.multiply(a,b)

array([ 4, 10, 18])

In [31]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [34]:
np.exp(b)


array([ 54.59815003, 148.4131591 , 403.42879349])

In [36]:
np.log(b)

array([1.38629436, 1.60943791, 1.79175947])

In [43]:
x=np.array([1,2,3])

In [44]:
np.sum(x)

6

In [45]:
np.mean(x)

2.0

In [46]:
np.prod(x)

6

In [49]:
c=np.array([[1,2,3],[4,5,6]])


In [50]:
np.sum(c,axis=1)

array([ 6, 15])

In [51]:
np.mean(c,axis=1)

array([2., 5.])

Linear Algebra

In [52]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [55]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [56]:
np.dot(a,b)

32

In [60]:
a=([1,2,3],[1,2,3])
b=([1,2,3])

In [61]:
np.matmul(a,b)

array([14, 14])

Statistical Functions

In [68]:
a=np.array([1,2,3])

In [69]:
np.std(a)

0.816496580927726

In [70]:
np.var(a)

0.6666666666666666

Reshape

In [72]:
a=np.array([[1,2,3],[4,5,6]])

In [73]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [75]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [76]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
a.resize(2,3)

In [81]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])